### ISSUE TITLE
Criar interface para trocar o ano

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#109]
A idéia é ter um select em alguma parte do menu com legenda Ano e na frente a possibilidade de escolher o ano que se quer operar. Novos chamado sempre serão no ano corrente, ao logar o usuário estará no contexto do ano corrente. Ao virar o ano o sistema muda automaticamente o ano e recomeça a contagem.

**Comment by fgmusp** [comment]
commit b7bad90809a1f8cd9b19c312e83293d738572138
