### ISSUE TITLE
Criar tabela patrimonio e chave estangeira para chamados

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#156]
assim será possivel rastrear um patrimonio quanto aos chamados abertos nele

**Comment by thiagogomesverissimo** [comment]
acho que não precisa criar uma tabela, mas apenas um tipo de campo no json chamdo patrimonio. Que serviria para:
- identificarmos e fazermos relatórios com patrimômonios
- Validar se é válido
- Se tiver On replicado, trazer algumas informações
- Buscar por patrimônios.

**Comment by thiagogomesverissimo** [comment]
Acho que sim =)

**Comment by fgmusp** [comment]
https://github.com/uspdev/chamados/commit/8b28af11d25bac03e41d728f7acb14e739f5cc07
