### ISSUE TITLE
relatorios

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#161]
qtd por período; 
qtd por fila;
por setor;
tempo entre a abertura e fechamento (conclusão) de um chamado.
 pode ficar para um segundo momento, ver sistema do IME como exemplo

**Comment by wgnann** [comment]
esse daqui não é o #19 ?

**Comment by masakik** [comment]
Criando relatório simples como card no show da fila, mostrando o nro de chamados por ano e por mês.
Também criando download dos chamados em xlsx com os principais campos para poder trabalhar estatística.
