### ISSUE TITLE
melhorar uso em mobile

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#163]
principalmente na rota de listagem de chamados e detalhes de um chamado. Alguns textos podem ser substituidos por icones em mobile e icone+texto em desktop

**Comment by masakik** [comment]
Menu lateral tipo adminlte pode ser legal

**Comment by fgmusp** [comment]
e7792999a2c5e90c0e5e5d6cd2d2207aa83b59c4

**Comment by fgmusp** [comment]
074409874a865383bcebecb3392bf8fb2ea89002
