### ISSUE TITLE
Gerar estatisticas de atendimentos das filas, tecnicos, setores, etc, para fins gerenciais

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/chamados#19]
https://si.ime.usp.br/cht/

**Comment by wgnann** [comment]
Aliás, quais estatísticas? Chamados por mês? Últimos chamados abertos? Chamados por categoria?

**Comment by thiagogomesverissimo** [comment]
Essas:

- Distribuição por Mês (mês atual e 6 meses passados)
- Distribuição por Mês (mês atual e 6 meses passados) - Fila de Notebooks

**Comment by masakik** [comment]
Essa tela para todos ou para os atendentes? Para usuário me parece muito poluído

**Comment by wgnann** [comment]
O que eu imaginei é o seguinte: **antes de logar**, o index mostra a situação atual dos chamados etc tal qual acontece no IME, mas para todos os chamados (dando a opção de filtrar por fila).

Depois de logar, pode ter uma view de estatísticas também.
