### ISSUE TITLE
Upload de imagens pelo celular

### ISSUE THREAD

**Issue by VirusABC** [uspdev/chamados#278]
Olá

Recentemente estava fazendo um teste e a função de adicionar imagens quando acessando o site de teste pelo celular não funcionou. Apareceram as opções de abrir a câmera do Android e tirar a foto, mas após tirar a foto nada acontecia. Adicionar uma imagem escolhendo um arquivo pelo celular também não.

Sistema: Android 9
Browsers testados: Chrome e Opera

Posso providenciar screenshots se necessário

**Comment by masakik** [comment]
Testei aqui agora e para mim funcionou. Em desktop funciona?

**Comment by VirusABC** [comment]
Hmmm, aaacho que o problema era meu celular... tentei aqui de novo e
não estava indo... mas aí dessa vez um dos navegadores que testei
informou um erro dizendo que não havia memória pra concluir a
operação... rebootei ele e deu certo.

E Sim, Desktop está funcionando bem.

Obrigado



Em Thu, 06 May 2021 06:58:44 -0700
Masaki Kawabata Neto ***@***.***> escreveu:

> Testei aqui agora e para mim funcionou. Em desktop funciona?
> 



-- 
Andre Lopes da Silva
Técnico em Informática
SI - IME-USP
3091-9891
Sala 120-A

Enviado utilizando Claws Mail
OpenSUSE Leap
