### ISSUE TITLE
Aceitar entrada de novos "Registros" vindo de respostas por e-mail

### ISSUE THREAD

**Issue by VirusABC** [uspdev/chamados#280]
Olá

Uma "feature request" seria se o sistema pudesse de alguma forma "receber" respostas feitas por e-mail e adicionasse essas respostas nos registros de um chamado

Exemplo: 
- Professor abre chamado: "Não consigo baixar torrent"
- Sistema envia e-mail para os responsáveis com título "chamado XXX Não consigo baixar torrent"
- Alguém designa um técnico para atender o chamado
- Sistema envia e-mail avisando a pessoa designada com título "Re: chamado XXX Não consigo baixar torrent"
- Técnico lê a mensagem e ao invés de entrar no sistema de chamados faz um "Responder Todos" avisando que o professor não irá conseguir baixar o torrent por motivo XXX no e-mail, de forma que esse responder todos vai chegar a todos: professor, técnicos e algum e-mail do sistema de chamados (imagino que seja necessário um e-mail do sistema de chamados para fazer isso que vou sugerir).
- E-mail de chamados detecta essa resposta recebida na caixa de entrada dele, verifica de qual chamado se refere através do assunto por exemplo e adiciona essa resposta do técnico nos registros do chamado.

Extra: Se isso for possível, será que também não seria possível operar o sistema por e-mail para algumas coisas? Exemplo: pessoa designada para atender o chamado escreve um e-mail para o endereço do sistema de chamados com algum comando por exemplo FECHAR CHAMADO: "Este chamado foi atendido comentário" e o sistema além de anotar no registro consegue fechar o chamado e avisar a todos.

Imagino que coisa assim possa acontecer em sistemas de helpdesk de empresas, onde os consumidores entram em um formulário para abrir chamado, recebem as respostas e vão interagindo com o atendente apenas por e-mail.

**Comment by thiagogomesverissimo** [comment]
Olá @VirusABC, 

Pensamos nessa feature em: https://github.com/uspdev/chamados/issues/79

Deixamos para segunda fase e eu particularmente sinto falta desse recurso.

Mas ao que parece esse pacote nos ajudaria muito:
https://github.com/beyondcode/laravel-mailbox

Podemos tentar fazer alguns testes com ele.
