### ISSUE TITLE
Ordenar exibição dos campos adicionados nas filas

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/chamados#298]
Movimentar os campos na interface e também editando o json parece não funcionar

**Comment by alecostaweb** [comment]
Aqui não ordena, na EESC funciona

**Comment by masakik** [comment]
isso estava no outro PR? podemos fechar?

**Comment by alecostaweb** [comment]
Não estava, mas pode fechar enquanto tento descobrir porque aqui não funciona.
