### ISSUE TITLE
migrar laravel 8

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#32]

**Comment by thiagogomesverissimo** [comment]
https://laravel.com/docs/8.x/upgrade

- composer:

    guzzlehttp/guzzle to ^7.0.1
    facade/ignition to ^2.3.6
    laravel/framework to ^8.0
    laravel/ui to ^3.0
    nunomaduro/collision to ^5.0
    phpunit/phpunit to ^9.0

- Seeders
- composer.json autoload
- index.php
- Rotas
- Factory
- Model
- Bootstrap:

```
use Illuminate\Pagination\Paginator;
public function boot()
{
    Paginator::useBootstrap();
}
```

**Comment by thiagogomesverissimo** [comment]
https://github.com/uspdev/chamados/commit/085ebc8917864c61c62f8af40aeabf0da8f60795
