### ISSUE TITLE
Chamados abertos de anos anteriores ficam escondidos

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#320]
A pessoa tem de mudar o ano para poder ver os chamados anteriores pendentes. 
Opções não exclusivas:
- Poderia haver um menu que mostrasse os pendentes;
- Pendentes poderiam ser incorporados à visualização corrente mas com indicação de ano;
- Poderia ter uma opção de fechamento automático global depois de xx dias de inatividade (90 dias por exemplo) ou configurável na fila (local)

**Comment by alecostaweb** [comment]
A primeira opção já resolveria a mudança de ano
