### ISSUE TITLE
transformar categoria em fila

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#33]

**Comment by wgnann** [comment]
você diz fazer filas distintas de chamados por categoria?

**Comment by masakik** [comment]
no sentido de mudar o nome

**Comment by masakik** [comment]
A ideia é um setor poder ter várias categorias ou no caso agora seria filas.

**Comment by masakik** [comment]
Criando uma tabela filas para depois poder migrar os dados das categorias e apagar
