### ISSUE TITLE
Tipo json do laravel transforma em longtext no mariadb

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#334]
como longtext um json mantém a ordemdos campos, mas no tipo json do mysql ele não mantem ordem.
Problema verificado no campo template da tabela filas.
É isso @alecostaweb ?

**Comment by masakik** [comment]
https://mariadb.com/kb/en/json-data-type/
Documentação do mariadb sobre json

**Comment by alecostaweb** [comment]
> como longtext um json mantém a ordemdos campos, mas no tipo json do mysql ele não mantem ordem. Problema verificado no campo template da tabela filas. É isso @alecostaweb ?

Isso mesmo

**Comment by masakik** [comment]
Foi adicionado a biblioteca ybr-nx/laravel-mariadb que potencialmente resolve isso. Mas não testei especificamente. De qualquer forma resolvemos de outra forma no código mas fica aqui o registro.
Vou acrescentar o driver mariadb no config->database para que possa ser usado essa extensão.
