### ISSUE TITLE
Ao logar, atualizar o vínculo

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/chamados#342]
O sistema guarda o vínculo no momento em que loga no sistema a primeira vez. Em situações onde o usuário troca de setor, o vínculo não é atualizado. Inclusive na lista de setores o usuário passa a aparecer em mais de um setor. Seria interessante permitir ao admin remover a pessoa do setor antigo.
Antes, verificar o impacto da mudança nas models com relação ao histórico de chamados da pessoa. O ideal é manter o setor antigo nos chamados já atendidos e usar o setor novo no momento da mudança.

**Comment by masakik** [comment]
o vinculo do usuario com o setor não guarda historico. Em algum momento funcionava. Depois de uma atualização da biblioteca da senhaunica parou de funcionar. Eu corrigi para atualizar novamente. Mas o chamado permanece vinculado à fila então não impacta em nada. O que muda, ao trocar de setor do usuário é a visibilidade das filas.
