### ISSUE TITLE
Aviso para atualizar ramal

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/chamados#356]
Sugestão de incluir o item abaixo no right_menu

```
    [
         'text' => '<i class="fas fa-phone"></i> Atualize seu telefone / ramal',
	 'url' => 'https://uspdigital.usp.br/telefonia/',
    ],
```

![Captura de tela de 2024-04-19 09-35-09](https://github.com/uspdev/chamados/assets/10613364/f9f70bad-cbed-4bbd-8bbb-bdd2b0405df4)

**Comment by masakik** [comment]
ficaria muito pesado mostrar o ramal atualmente cadastrado? para a pessoa ao visualizar já saber se precisa alterar ou não.

**Comment by alecostaweb** [comment]
![Captura de tela de 2024-04-19 15-17-21](https://github.com/uspdev/chamados/assets/10613364/f31162c4-9a6c-46bd-be05-28c9910612e0)

Que tal assim?

**Comment by alecostaweb** [comment]
![image](https://github.com/uspdev/chamados/assets/10613364/0ff3b267-a149-4fdc-9486-214e111445e2)

Acho que fica melhor assim, no laravel-usp-theme e acaba servindo em todos os sistemas.
O que acha?

**Comment by alecostaweb** [comment]
Vou implementar no laravel-usp-theme somente no skin da ECA
