### ISSUE TITLE
atendentes estão hardcoded no app/Chamado.php

### ISSUE THREAD

**Issue by wgnann** [uspdev/chamados#36]
deveria puxar as informações dos usuários do sistema. talvez implementar um mecanismo de grupo tal qual existe no copaco para escolher quem aparecerá lá.

**Comment by wgnann** [comment]
em tempo. talvez os prédios também devessem ser um modelo

**Comment by thiagogomesverissimo** [comment]
puxaremos prédios do .env?
ou puxaremos de um json ?

**Comment by thiagogomesverissimo** [comment]
os atendentes virão do grupo que administra a fila

**Comment by masakik** [comment]
Resolvido na reorganização do chamado
