### ISSUE TITLE
campo para observações dos atendentes no chamado

### ISSUE THREAD

**Issue by wgnann** [uspdev/chamados#39]
eventualmente tem coisa que acaba indo de um dia para outro e é importante deixar algumas anotações sobre em que pé que está o atendimento

**Comment by masakik** [comment]
Também ficaria nos comentários. Pois tanto o atendente quanto o usuário poderiam escrever lá.

**Comment by wgnann** [comment]
aí que está. temos um esquema de uso onde alguns comentários mais técnicos ficam no sistema "só para nós" para sabermos em que pé que está o atendimento etc. o comentário não atende justamente por publicar tudo.

**Comment by masakik** [comment]
Entendi

**Comment by wgnann** [comment]
Talvez seja razoável deixar uma margem para customizar o formulário de atendimento por setor ou por fila. Seria algo na linha dos dynamic attributes.

**Comment by wgnann** [comment]
resolvido com a implementação dos templates
