### ISSUE TITLE
campos para atendimento na ausência do usuário e horário de atendimento preferido

### ISSUE THREAD

**Issue by wgnann** [uspdev/chamados#40]
no IME temos uma prática de eventualmente retirar a máquina e levar para nosso laboratório (quando há anuência do responsável) ou mesmo de verificar situações in loco (e.g. driver de impressora) mesmo que ele não esteja presente.

além disso, há o campo de horário para combinar atendimento em determinadas situações

**Comment by masakik** [comment]
Esse caso não caberia nos comentários? Tipo: gostaria de retirar o equipamento dia x hora y. Aí o usuário confirma ou não.

**Comment by wgnann** [comment]
Se isso de alguma forma estiver no corpo da mensagem do chamado, funciona. O problema é que se não estiver indicado em nenhum lugar, criará uma ineficiência no workflow de atendimento.

Workflow esperado:
1. o usuário abre o chamado preenchendo com as infos de horário e ausência;
2. a seção se programa para haver tal atendimento.

Workflow possível:
1. o usuário abre o chamado;
2. o atendente olha o chamado e manda uma mensagem (quase automática) para o usuário;
3. o usuário recebe a mensagem e responde se poderá ser atendido com horário e ausência;
4. o atendente recebe essa informação e a seção se programa para haver tal atendimento.

**Comment by wgnann** [comment]
considerando que o objetivo é atender mais filas, talvez não faça sentido manter como geral esse par de campos que só diz respeito ao workflow da seção de informática

**Comment by wgnann** [comment]
resolvido com a implementação dos templates.
