### ISSUE TITLE
regressões no update para o laravel8

### ISSUE THREAD

**Issue by wgnann** [uspdev/chamados#41]
o form de categorias está com um campo "Usuário" a mais e parece ter perdido formatação

a rota para o UserController (/users) parou de funcionar

logout também parou de funcionar

**Comment by thiagogomesverissimo** [comment]
- Essa campo de usuário deixei sem querer...
- Corrigi o namespace UserController
- Para o logout funcionar, no app_env do .env colocar a url da sua aplicação:, tipo localhost:8000
