### ISSUE TITLE
container descentralizado e web.php sem ComentarioController

### ISSUE THREAD

**Issue by wgnann** [uspdev/chamados#42]

**Comment by masakik** [comment]
Não entendi aqui.

**Comment by wgnann** [comment]
1) antes das atualizações para o laravel 8 (e outras atualizações que foram no mesmo commit), o `<div id=container>` ficava centralizado bonitinho. agora está esticando até as margens da página.

2) o sistema não está salvando comentários porque precisa referenciar o `ComentarioController` no `web.php`

**Comment by wgnann** [comment]
entendi. mudou de `class=container` para `class=container-fluid`. estou vendo qual a diferença entre ambos.
