### ISSUE TITLE
tratar ao adicionar usuario inexistente 

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#43]

**Comment by wgnann** [comment]
Como assim?

**Comment by masakik** [comment]
No menu usuarios, ao adicionar atendente por nro usp com um numero inexistente ele não retorna uma mensagem mas uma tela de erro. De qualquer forma eu pretendo reescrever toda a parte de atendentes transformando em relacionamento n:n entre categorias/filas e users.

**Comment by wgnann** [comment]
acho que isso ficou pronto criando usuários do replicado (ou exigindo usuários existentes no caso de não usar replicado)
