### ISSUE TITLE
permitir upload de arquivo no chamado

### ISSUE THREAD

**Issue by wgnann** [uspdev/chamados#51]

**Comment by masakik** [comment]
permitir pdf e fotos
relacionado com chamados

**Comment by thiagogomesverissimo** [comment]
Essa o @st-ricardof está implementando

**Comment by masakik** [comment]
seria interessante colocar os arquivos em pastas por ano no file system? Porque os chamados serão organizados por ano e dessa forma limitaria o nro de arquivos por pasta.

**Comment by st-ricardof** [comment]
Feito, mas não cheguei a implementar essa separação por anos. Devo colocá-la então?

**Comment by thiagogomesverissimo** [comment]
Acho que sim. É simples, basta no store pegar o ano atual e passar como parâmetro
