### ISSUE TITLE
tabela chamados -> atribuido_para poderia ir para tabela de relacionamento chamado_user

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#59]
aí iria também triagem_por e atribuido_em.
Manteria complexidade

**Comment by wgnann** [comment]
do jeito que está agora, o que se preenche é um nusp.

para trocar, precisará:

1. trocar a lógica do procedimento de triagem para preencher a tabela de relacionamento;
2. alterar todos os views que leem esses campos.
