### ISSUE TITLE
refatorar tabela chamados

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#72]

**Comment by wgnann** [comment]
precisa resolver os detalhes do issue #59 para terminar. se eu meramente limar os campos, precisaremos consertar as coisas ou o sistema todo ficará quebrado no commit.

**Comment by masakik** [comment]
Acho que limpa tudo. O que quebrar deixa pro povo do front corrigir.

Em qui, 15 de out de 2020 09:13, wgnann <notifications@github.com> escreveu:

**Comment by masakik** [comment]
feito
