### ISSUE TITLE
formulário dinâmico - permitir campos select

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#75]
permitir definir se um campo é obrigatório

**Comment by masakik** [comment]
campo select tem que tomar cuidado com a Validação, no caos, validar com Rule::in($array_options)
    permitir campos obrigatórios (esse precisará de marcação no json e de validação)
    formulario para gerar o form dinâmico (text, date, select) na tela da fila

**Comment by wgnann** [comment]
meio pronto. falta ver um jeito melhor para fazer isso na interface de usuário

**Comment by wgnann** [comment]
acho que pode fechar
