### ISSUE TITLE
criar relacionamento chamado-chamado

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#77]
Permite que um chamado referencie outro chamado que dependa dele
    pivot->acesso
        leitura, completo
precisa definir direitinho como ficará o many to many aqui

**Comment by wgnann** [comment]
ia ver isso ontem, mas precisaremos definir como serão chamados os campos etc, já que não podemos meramente usar `chamado_id` duas vezes. talvez compense usar um acessor com nome diferente para dizer qual é a semântica. do jeito padrão ficaria `$chamado->chamados`, que é meio estranho. uma possibilidade seria `$chamado->vinculados`, mas eu não sei se faz sentido implementar o acessor no outro sentido, tal qual faríamos com um n2n usual.

**Comment by masakik** [comment]
No setor eu chamei o campo de pai. Achei que ficou legal. Vinculados me parece uma boa opção.

**Comment by wgnann** [comment]
no setor é vários setores filhos para um setor pai. no chamados a ideia é a mesma? porque, se for, não precisa de uma relação nova para cuidar disso.

**Comment by masakik** [comment]
no chamado a idéia é ser many to many mesmo de forma que cada chamado possa referenciar quaisquer outros.
