### ISSUE TITLE
Fila está pedindo campo estado que não foi definido

### ISSUE THREAD

**Issue by wgnann** [uspdev/chamados#95]

**Comment by thiagogomesverissimo** [comment]
não consegui reproduzir.. em que momento?

**Comment by wgnann** [comment]
rodei o `migrate:fresh --seed`
lá:

1. loguei
2. virei admin
3. Fila / Nova Fila
4. Preenchi, submit e ele falha dizendo que `filas.estado` não pode ser NULL.

**Comment by thiagogomesverissimo** [comment]
mas não tem o campo estado no model Fila. Você não está criando um chamado?

**Comment by wgnann** [comment]
Tem sim: https://github.com/uspdev/chamados/blob/0e92dfd3edccb736b9d9b7f04cb8f463fc53060f/database/migrations/2020_09_28_161446_create_filas_table.php#L19

![image](https://user-images.githubusercontent.com/1002642/96500021-99991080-1224-11eb-84b1-b90481a079f4.png)

**Comment by masakik** [comment]
aparentemente deve acontecer no sqlite. no mysql ele usa o primeiro valor de enum como default
