### ISSUE TITLE
Upload de arquivos - ajustes

### ISSUE THREAD

**Issue by masakik** [uspdev/chamados#98]
- fazer relacionamento com user para saber quem enviou o arquivo;
- ao enviar um arquivo registrar nos comentário essa ação, similar à atribuição de atendente. Ao excluir também;
- Depois de escolher o arquivo no form, poderia submeter imediatamente sem ter de confirmar novamente;
- permitir alterar o nome de exibição (pdf), tipo um campo "texto" que será exibido no lugar do nome do arquivo. Rotina: usuário envia arquivo e depois altera a exibição para uma descrição mais significativa que o nome do arquivo. Caso usuário não coloque deve exibir o nome (video no telegram);
- separar arquivos no FS por ano;
- gerar mensagem flash;

**Comment by wgnann** [comment]
relacionamento ok. precisa botar os gates/cans

**Comment by masakik** [comment]
Acho que o Ricardo está mexendo nessa issue também @wgnann

**Comment by wgnann** [comment]
ah sim. só mexi na migration pq já ia mexer em migrations por causa da outra issue e pq ia escrever que os usuários podem acessar arquivos uns dos outros.
