### ISSUE TITLE
ordenação do número do chamado não é numérica

### ISSUE THREAD

**Issue by wgnann** [uspdev/chamados#99]
está ordenando de forma lexicográfica

**Comment by masakik** [comment]
se tirar o ano fica certinho. Acho que é uma opção

**Comment by fgmusp** [comment]
Resolve??
`
oTable = $('.meus-chamados').DataTable({
      dom: 't',
      "paging": false,
      "sort": true,
      "order": [[4, "desc"]]  /* coluna created_at */
    });
`
